// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/signin": {
    params: {};
  };
  "/signout": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/settings": {
    params: {};
  };
  "/customers": {
    params: {};
  };
  "/customers/:id": {
    params: {
      "id": string;
    };
  };
  "/users": {
    params: {};
  };
  "/users/:id": {
    params: {
      "id": string;
    };
  };
  "/products": {
    params: {};
  };
  "/products/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/signin" | "/signout" | "/admin" | "/admin/settings" | "/customers" | "/customers/:id" | "/users" | "/users/:id" | "/products" | "/products/:id";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/auth/signin.tsx": {
    id: "routes/auth/signin";
    page: "/signin";
  };
  "routes/auth/signout.tsx": {
    id: "routes/auth/signout";
    page: "/signout";
  };
  "routes/admin/index.tsx": {
    id: "routes/admin/index";
    page: "/admin";
  };
  "routes/admin/settings.tsx": {
    id: "routes/admin/settings";
    page: "/admin/settings";
  };
  "routes/customers/index.tsx": {
    id: "routes/customers/index";
    page: "/customers";
  };
  "routes/customers/[id]/index.tsx": {
    id: "routes/customers/[id]/index";
    page: "/customers/:id";
  };
  "routes/users/index.tsx": {
    id: "routes/users/index";
    page: "/users";
  };
  "routes/users/[id]/index.tsx": {
    id: "routes/users/[id]/index";
    page: "/users/:id";
  };
  "routes/products/index.tsx": {
    id: "routes/products/index";
    page: "/products";
  };
  "routes/products/[id]/index.tsx": {
    id: "routes/products/[id]/index";
    page: "/products/:id";
  };
};